/**
 * Engager Recruitment API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTaskResponse {
    title: string;
    due?: Date;
    completedAt?: Date;
    status: CreateTaskResponse.StatusEnum;
    id: string;
    createdAt: Date;
}
export namespace CreateTaskResponse {
    export const StatusEnum = {
        Open: 'OPEN',
        Done: 'DONE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


