/**
 * Engager Recruitment API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetTasksResponseMeta } from './getTasksResponseMeta';
import { CreateTaskResponse } from './createTaskResponse';


export interface GetTasksResponse { 
    /**
     * Array of tasks
     */
    data: Array<CreateTaskResponse>;
    /**
     * Pagination metadata
     */
    meta: GetTasksResponseMeta;
}

