/**
 * Engager Recruitment API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetTasksResponseMeta { 
    /**
     * Next cursor for pagination
     */
    nextCursor: object | null;
    /**
     * True if more tasks are available
     */
    hasMore: boolean;
}

