/**
 * Engager Recruitment API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTaskDto { 
    title?: string;
    due?: string;
    completedAt?: string;
    status?: UpdateTaskDto.StatusEnum;
}
export namespace UpdateTaskDto {
    export const StatusEnum = {
        Open: 'OPEN',
        Done: 'DONE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


